version: '3'
networks:
  zabbix-proxy:
    external: true
services:
  proxy-mysql:
    image: mysql:8.0
    container_name: mysql-proxy-${PNAME}-5.2.6
    restart: always
    command:
      --character-set-server=utf8
      --collation-server=utf8_bin
      --default-authentication-plugin=mysql_native_password
      --binlog_expire_logs_seconds=604800
      --log_error=error.log
      --slow_query_log=1
      --slow_query_log_file=slow.log
      --log_queries_not_using_indexes=1
      --log_slow_admin_statements=1
      --log_slow_slave_statements=1
      --log_throttle_queries_not_using_indexes=10
      --long_query_time=2
      --min_examined_row_limit=100  
    networks:
      - zabbix-proxy
    ports:
      - '${MPORT}:3306'
    environment:
      MYSQL_DATABASE: zabbix_proxy
      MYSQL_USER: zabbix_proxy
      MYSQL_PASSWORD: zabbix_proxy
      MYSQL_ROOT_PASSWORD: Capinfo@123
    volumes:
      - /data/zabbix_data/mysql_proxy_${PNAME}:/var/lib/mysql

  proxy:
    image: hub.jgswy.com/zabbix/zabbix-proxy-5.2.6:v1
    container_name: zabbix-proxy-${PNAME}-5.2.6
    restart: always
    networks:
      - zabbix-proxy
    ports:
      - '${PPORT}:10051'
    environment:
      DB_SERVER_HOST: mysql-proxy-${PNAME}-5.2.6
      MYSQL_DATABASE: zabbix_proxy
      MYSQL_USER: zabbix_proxy
      MYSQL_PASSWORD: zabbix_proxy
      ZBX_HOSTNAME: zabbix-proxy-${PNAME}
      ZBX_SERVER_HOST: ${ZBX_SERVER_IP}
      ZBX_SERVER_PORT: 10051
      ZBX_CACHESIZE: 256M
      ZBX_CONFIGFREQUENCY: 60
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - proxy-mysql
